//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Boutique.Models.MyModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public string tentaikhoan { get; set; }
        public string matkhau { get; set; }
        public string hoten { get; set; }
        public string gioitinh { get; set; }
        public string email { get; set; }
        public string sdt { get; set; }
        public string quyenhan { get; set; }
    }
}
