//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Boutique.Models.MyModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public int masp { get; set; }
        public string tensp { get; set; }
        public Nullable<int> giagocsp { get; set; }
        public Nullable<int> maloaisp { get; set; }
        public Nullable<int> giabansp { get; set; }
        public Nullable<System.DateTime> ngaynhapsp { get; set; }
        public Nullable<int> soluongsp { get; set; }
        public string motasp { get; set; }
        public string anhsp { get; set; }
        public string tinhtrangsp { get; set; }
        public string size { get; set; }
    
        public virtual LoaiSanPham LoaiSanPham { get; set; }
    }
}
